services:
  - type: web
    name: email-verification
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd front && npm install && CI=false npm run build && cd ..
      python manage.py collectstatic --noinput
    startCommand: gunicorn email_ver.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 8000
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_API_KEY
        sync: false