services:
  - type: web
    name: email-verification
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd front && npm install && npm run build
      python manage.py collectstatic --noinput
    startCommand: gunicorn email_ver.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_API_KEY
        sync: false